version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "npm"
      - "dependencies"
    assignees:
      - "PhongGuy"

  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "weekly"
    labels:
      - "npm"
      - "dependencies"
    assignees:
      - "PhongGuy"
