version = 1

exclude_patterns = [
  "docs/**",
  ".github/**",
  ".vscode/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["angular"]

[[transformers]]
name = "standardjs"
enabled = true