# This is a basic workflow to help you get started with Actions
name: autoupdate

# Controls when the action will run.
on:
  # This will trigger on all pushes to all branches.
  push: {}

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-20.04
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: "${{ secrets.PHONG_TOKEN }}"
          PR_FILTER: "labelled"
          PR_LABELS: "autoupdate"
          EXCLUDED_LABELS: "wontfix"
