# This is a basic workflow to help you get started with Actions

name: Stale Issues

# Controls when the workflow will run
on:
  workflow_dispatch:
    schedule:
      - cron: '0 0 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Close issues and pull requests with no recent activity
      - name: Close Stale Issues
        uses: actions/stale@v9.0.0
        with:
          days-before-stale: 30
          days-before-close: 5
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label, comment or this will be closed in 5 days'
